version: "3.9"
services:
  app:
    build: app
    volumes:
      - ./app:/app
    command: sleep infinity
#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_DATABASE: "test"
#      MYSQL_USER: "user"
#      MYSQL_PASSWORD: "userpass"
#    ports:
#      - 3306:3306

